In [5]:
import pandas as pd
from datetime import datetime

df_customer = pd.read_csv('Microsoft/AWCustomers.csv')
df_sales = pd.read_csv('Microsoft/AWSales.csv')

merged_df = pd.merge(df_customer, df_sales, on='CustomerID')

merged_df['BirthDate'] = pd.to_datetime(merged_df['BirthDate'])

merged_df['Age'] = ((datetime.now() - merged_df['BirthDate']).dt.days / 365.25).astype(int)

new_df = merged_df[[
    'BikeBuyer', 'YearlyIncome', 'Gender', 'MaritalStatus', 'Age', 'Education',
    'Occupation', 'HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome',
    'TotalChildren', 'CountryRegionName', 'StateProvinceName'
]]

print(new_df.head().to_markdown(index=False, numalign="left", stralign="left"))

| BikeBuyer   | YearlyIncome   | Gender   | MaritalStatus   | Age   | Education       | Occupation     | HomeOwnerFlag   | NumberCarsOwned   | NumberChildrenAtHome   | TotalChildren   | CountryRegionName   | StateProvinceName   |
|:------------|:---------------|:---------|:----------------|:------|:----------------|:---------------|:----------------|:------------------|:-----------------------|:----------------|:--------------------|:--------------------|
| 1           | 81916          | M        | M               | 36    | Bachelors       | Clerical       | 1               | 3                 | 0                      | 1               | Australia           | New South Wales     |
| 1           | 81076          | M        | M               | 52    | Partial College | Clerical       | 1               | 2                 | 1                      | 2               | Canada              | British Columbia    |
| 1           | 86387          | F        | S               | 38    | Bachelors       | Clerical       | 0               | 3                 | 0                      | 0               | United States       | California          |
| 1           | 61481          | M        | M               | 46    | Partial College | Skilled Manual | 1               | 2                 | 1                      | 2               | United Kingdom      | England             |
| 1           | 51804          | M        | S               | 49    | Partial College | Skilled Manual | 1               | 1                 | 0                      | 0               | Germany             | Nordrhein-Westfalen |

In [4]:
import pandas as pd

df_customer = pd.read_csv('Microsoft/AWCustomers.csv')
df_sales = pd.read_csv('Microsoft/AWSales.csv')


print("First 5 rows of AWCustomers.csv:")
print(df_customer.head().to_markdown(index=False, numalign="left", stralign="left"))

print("\nColumn names and their data types for AWCustomers.csv:")
print(df_customer.info())

print("\nFirst 5 rows of AWSales.csv:")
print(df_sales.head().to_markdown(index=False, numalign="left", stralign="left"))

print("\nColumn names and their data types for AWSales.csv:")
print(df_sales.info())

First 5 rows of AWCustomers.csv:
| CustomerID   | Title   | FirstName   | MiddleName   | LastName   | Suffix   | AddressLine1           | AddressLine2   | City        | StateProvinceName   | CountryRegionName   | PostalCode   | PhoneNumber         | BirthDate   | Education       | Occupation     | Gender   | MaritalStatus   | HomeOwnerFlag   | NumberCarsOwned   | NumberChildrenAtHome   | TotalChildren   | YearlyIncome   | LastUpdated   |
|:-------------|:--------|:------------|:-------------|:-----------|:---------|:-----------------------|:---------------|:------------|:--------------------|:--------------------|:-------------|:--------------------|:------------|:----------------|:---------------|:---------|:----------------|:----------------|:------------------|:-----------------------|:----------------|:---------------|:--------------|
| 21173        | nan     | Chad        | C            | Yuan       | nan      | 7090 C. Mount Hood     | nan            | Wollongong  | New South Wales     | Australia           | 2500         | 1 (11) 500 555-0115 | 1987-11-13  | Bachelors       | Clerical       | M        | M               | 1               | 3                 | 0                      | 1               | 81916          | 2017-03-06    |
| 13249        | nan     | Ryan        | nan          | Perry      | nan      | 3651 Willow Lake Rd    | nan            | Shawnee     | British Columbia    | Canada              | V9B 2C3      | 787-555-0136        | 1972-07-21  | Partial College | Clerical       | M        | M               | 1               | 2                 | 1                      | 2               | 81076          | 2017-03-06    |
| 29350        | nan     | Julia       | nan          | Thompson   | nan      | 1774 Tice Valley Blvd. | nan            | West Covina | California          | United States       | 91791        | 120-555-0111        | 1985-11-09  | Bachelors       | Clerical       | F        | S               | 0               | 3                 | 0                      | 0               | 86387          | 2017-03-06    |
| 13503        | nan     | Theodore    | nan          | Gomez      | nan      | 2103 Baldwin Dr        | nan            | Liverpool   | England             | United Kingdom      | L4 4HB       | 1 (11) 500 555-0167 | 1977-10-18  | Partial College | Skilled Manual | M        | M               | 1               | 2                 | 1                      | 2               | 61481          | 2017-03-06    |
| 22803        | nan     | Marshall    | J            | Shan       | nan      | Am Gallberg 234        | nan            | Werne       | Nordrhein-Westfalen | Germany             | 59368        | 1 (11) 500 555-0113 | 1975-02-05  | Partial College | Skilled Manual | M        | S               | 1               | 1                 | 0                      | 0               | 51804          | 2017-03-06    |

Column names and their data types for AWCustomers.csv:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18361 entries, 0 to 18360
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            18361 non-null  int64
 1   Title                 101 non-null    object
 2   FirstName             18361 non-null  object
 3   MiddleName            10572 non-null  object
 4   LastName              18361 non-null  object
 5   Suffix                3 non-null      object
 6   AddressLine1          18361 non-null  object
 7   AddressLine2          311 non-null    object
 8   City                  18361 non-null  object
 9   StateProvinceName     18361 non-null  object
 10  CountryRegionName     18361 non-null  object
 11  PostalCode            18361 non-null  object
 12  PhoneNumber           18361 non-null  object
 13  BirthDate             18361 non-null  object
 14  Education             18361 non-null  object
 15  Occupation            18361 non-null  object
 16  Gender                18361 non-null  object
 17  MaritalStatus         18361 non-null  object
 18  HomeOwnerFlag         18361 non-null  int64
 19  NumberCarsOwned       18361 non-null  int64
 20  NumberChildrenAtHome  18361 non-null  int64
 21  TotalChildren         18361 non-null  int64
 22  YearlyIncome          18361 non-null  int64
 23  LastUpdated           18361 non-null  object
dtypes: int64(6), object(18)
memory usage: 3.4+ MB
None

First 5 rows of AWSales.csv:
| CustomerID   | BikeBuyer   | AvgMonthSpend   |
|:-------------|:------------|:----------------|
| 21173        | 1           | 50.97           |
| 13249        | 1           | 53.11           |
| 29350        | 1           | 54.08           |
| 13503        | 1           | 56.93           |
| 22803        | 1           | 55.41           |

Column names and their data types for AWSales.csv:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18355 entries, 0 to 18354
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     18355 non-null  int64
 1   BikeBuyer      18355 non-null  int64
 2   AvgMonthSpend  18355 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 430.3 KB
None

In [3]:
from datetime import datetime
from sklearn.preprocessing import MinMaxScaler, KBinsDiscretizer
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df_customer = pd.read_csv('Microsoft/AWCustomers.csv')
df_sales = pd.read_csv('Microsoft/AWSales.csv')

# Merge the DataFrames on 'CustomerID'
merged_df = pd.merge(df_customer, df_sales, on='CustomerID')

# Convert 'BirthDate' to datetime
merged_df['BirthDate'] = pd.to_datetime(merged_df['BirthDate'])

# Calculate 'Age'
merged_df['Age'] = ((datetime.now() - merged_df['BirthDate']).dt.days / 365.25).astype(int)

# Select the relevant columns
new_df = merged_df[[
    'BikeBuyer', 'YearlyIncome', 'Gender', 'MaritalStatus', 'Age', 'Education',
    'Occupation', 'HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome',
    'TotalChildren', 'CountryRegionName', 'StateProvinceName'
]].copy()

# Display the first 5 rows of the new DataFrame
print("First 5 rows of the new DataFrame:")
print(new_df.head().to_markdown(index=False, numalign="left", stralign="left"))

# Check if there are any null values in the new dataframe
print("\nAre there any null values in the new dataframe?")
print(new_df.isnull().values.any())

# Normalization
scaler = MinMaxScaler()
new_df['YearlyIncome_scaled'] = scaler.fit_transform(new_df[['YearlyIncome']])
new_df['Age_scaled'] = scaler.fit_transform(new_df[['Age']])

# Discretization (Binning)
discretizer = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='quantile')
new_df['YearlyIncome_binned'] = discretizer.fit_transform(new_df[['YearlyIncome_scaled']])

# One Hot Encoding
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded_data = encoder.fit_transform(new_df[['Gender', 'MaritalStatus', 'Education', 'Occupation', 'CountryRegionName', 'StateProvinceName']])
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(['Gender', 'MaritalStatus', 'Education', 'Occupation', 'CountryRegionName', 'StateProvinceName']))

# Concatenate the one hot encoded columns with the rest of the dataframe
final_df = pd.concat([new_df, encoded_df], axis=1)

# Drop the original categorical columns
final_df.drop(['Gender', 'MaritalStatus', 'Education', 'Occupation', 'CountryRegionName', 'StateProvinceName'], axis=1, inplace=True)

# Display the first 5 rows of the final dataframe
print("\nFirst 5 rows of the final dataframe:")
print(final_df.head().to_markdown(index=False, numalign="left", stralign="left"))

First 5 rows of the new DataFrame:
| BikeBuyer   | YearlyIncome   | Gender   | MaritalStatus   | Age   | Education       | Occupation     | HomeOwnerFlag   | NumberCarsOwned   | NumberChildrenAtHome   | TotalChildren   | CountryRegionName   | StateProvinceName   |
|:------------|:---------------|:---------|:----------------|:------|:----------------|:---------------|:----------------|:------------------|:-----------------------|:----------------|:--------------------|:--------------------|
| 1           | 81916          | M        | M               | 36    | Bachelors       | Clerical       | 1               | 3                 | 0                      | 1               | Australia           | New South Wales     |
| 1           | 81076          | M        | M               | 52    | Partial College | Clerical       | 1               | 2                 | 1                      | 2               | Canada              | British Columbia    |
| 1           | 86387          | F        | S               | 38    | Bachelors       | Clerical       | 0               | 3                 | 0                      | 0               | United States       | California          |
| 1           | 61481          | M        | M               | 46    | Partial College | Skilled Manual | 1               | 2                 | 1                      | 2               | United Kingdom      | England             |
| 1           | 51804          | M        | S               | 49    | Partial College | Skilled Manual | 1               | 1                 | 0                      | 0               | Germany             | Nordrhein-Westfalen |

Are there any null values in the new dataframe?
False

First 5 rows of the final dataframe:
| BikeBuyer   | YearlyIncome   | Age   | HomeOwnerFlag   | NumberCarsOwned   | NumberChildrenAtHome   | TotalChildren   | YearlyIncome_scaled   | Age_scaled   | YearlyIncome_binned   | Gender_F   | Gender_M   | MaritalStatus_M   | MaritalStatus_S   | Education_Bachelors   | Education_Graduate Degree   | Education_High School   | Education_Partial College   | Education_Partial High School   | Occupation_Clerical   | Occupation_Management   | Occupation_Manual   | Occupation_Professional   | Occupation_Skilled Manual   | CountryRegionName_Australia   | CountryRegionName_Canada   | CountryRegionName_France   | CountryRegionName_Germany   | CountryRegionName_United Kingdom   | CountryRegionName_United States   | StateProvinceName_Alabama   | StateProvinceName_Alberta   | StateProvinceName_Arizona   | StateProvinceName_Bayern   | StateProvinceName_Brandenburg   | StateProvinceName_British Columbia   | StateProvinceName_California   | StateProvinceName_Charente-Maritime   | StateProvinceName_England   | StateProvinceName_Essonne   | StateProvinceName_Florida   | StateProvinceName_Garonne (Haute)   | StateProvinceName_Georgia   | StateProvinceName_Hamburg   | StateProvinceName_Hauts de Seine   | StateProvinceName_Hessen   | StateProvinceName_Illinois   | StateProvinceName_Kentucky   | StateProvinceName_Loir et Cher   | StateProvinceName_Loiret   | StateProvinceName_Maryland   | StateProvinceName_Massachusetts   | StateProvinceName_Minnesota   | StateProvinceName_Mississippi   | StateProvinceName_Missouri   | StateProvinceName_Montana   | StateProvinceName_Moselle   | StateProvinceName_New South Wales   | StateProvinceName_New York   | StateProvinceName_Nord   | StateProvinceName_Nordrhein-Westfalen   | StateProvinceName_North Carolina   | StateProvinceName_Ohio   | StateProvinceName_Ontario   | StateProvinceName_Oregon   | StateProvinceName_Pas de Calais   | StateProvinceName_Queensland   | StateProvinceName_Saarland   | StateProvinceName_Seine (Paris)   | StateProvinceName_Seine Saint Denis   | StateProvinceName_Seine et Marne   | StateProvinceName_Somme   | StateProvinceName_South Australia   | StateProvinceName_South Carolina   | StateProvinceName_Tasmania   | StateProvinceName_Texas   | StateProvinceName_Utah   | StateProvinceName_Val d'Oise   | StateProvinceName_Val de Marne   | StateProvinceName_Victoria   | StateProvinceName_Virginia   | StateProvinceName_Washington   | StateProvinceName_Wyoming   | StateProvinceName_Yveline   |
|:------------|:---------------|:------|:----------------|:------------------|:-----------------------|:----------------|:----------------------|:-------------|:----------------------|:-----------|:-----------|:------------------|:------------------|:----------------------|:----------------------------|:------------------------|:----------------------------|:--------------------------------|:----------------------|:------------------------|:--------------------|:--------------------------|:----------------------------|:------------------------------|:---------------------------|:---------------------------|:----------------------------|:-----------------------------------|:----------------------------------|:----------------------------|:----------------------------|:----------------------------|:---------------------------|:--------------------------------|:-------------------------------------|:-------------------------------|:--------------------------------------|:----------------------------|:----------------------------|:----------------------------|:------------------------------------|:----------------------------|:----------------------------|:-----------------------------------|:---------------------------|:-----------------------------|:-----------------------------|:---------------------------------|:---------------------------|:-----------------------------|:----------------------------------|:------------------------------|:--------------------------------|:-----------------------------|:----------------------------|:----------------------------|:------------------------------------|:-----------------------------|:-------------------------|:----------------------------------------|:-----------------------------------|:-------------------------|:----------------------------|:---------------------------|:----------------------------------|:-------------------------------|:-----------------------------|:----------------------------------|:--------------------------------------|:-----------------------------------|:--------------------------|:------------------------------------|:-----------------------------------|:-----------------------------|:--------------------------|:-------------------------|:-------------------------------|:---------------------------------|:-----------------------------|:-----------------------------|:-------------------------------|:----------------------------|:----------------------------|
| 1           | 81916          | 36    | 1               | 3                 | 0                      | 1               | 0.496842              | 0.183099     | 3                     | 0          | 1          | 1                 | 0                 | 1                     | 0                           | 0                       | 0                           | 0                               | 1                     | 0                       | 0                   | 0                         | 0                           | 1                             | 0                          | 0                          | 0                           | 0                                  | 0                                 | 0                           | 0                           | 0                           | 0                          | 0                               | 0                                    | 0                              | 0                                     | 0                           | 0                           | 0                           | 0                                   | 0                           | 0                           | 0                                  | 0                          | 0                            | 0                            | 0                                | 0                          | 0                            | 0                                 | 0                             | 0                               | 0                            | 0                           | 0                           | 1                                   | 0                            | 0                        | 0                                       | 0                                  | 0                        | 0                           | 0                          | 0                                 | 0                              | 0                            | 0                                 | 0                                     | 0                                  | 0                         | 0                                   | 0                                  | 0                            | 0                         | 0                        | 0                              | 0                                | 0                            | 0                            | 0                              | 0                           | 0                           |
| 1           | 81076          | 52    | 1               | 2                 | 1                      | 2               | 0.489453              | 0.408451     | 3                     | 0          | 1          | 1                 | 0                 | 0                     | 0                           | 0                       | 1                           | 0                               | 1                     | 0                       | 0                   | 0                         | 0                           | 0                             | 1                          | 0                          | 0                           | 0                                  | 0                                 | 0                           | 0                           | 0                           | 0                          | 0                               | 1                                    | 0                              | 0                                     | 0                           | 0                           | 0                           | 0                                   | 0                           | 0                           | 0                                  | 0                          | 0                            | 0                            | 0                                | 0                          | 0                            | 0                                 | 0                             | 0                               | 0                            | 0                           | 0                           | 0                                   | 0                            | 0                        | 0                                       | 0                                  | 0                        | 0                           | 0                          | 0                                 | 0                              | 0                            | 0                                 | 0                                     | 0                                  | 0                         | 0                                   | 0                                  | 0                            | 0                         | 0                        | 0                              | 0                                | 0                            | 0                            | 0                              | 0                           | 0                           |
| 1           | 86387          | 38    | 0               | 3                 | 0                      | 0               | 0.536172              | 0.211268     | 3                     | 1          | 0          | 0                 | 1                 | 1                     | 0                           | 0                       | 0                           | 0                               | 1                     | 0                       | 0                   | 0                         | 0                           | 0                             | 0                          | 0                          | 0                           | 0                                  | 1                                 | 0                           | 0                           | 0                           | 0                          | 0                               | 0                                    | 1                              | 0                                     | 0                           | 0                           | 0                           | 0                                   | 0                           | 0                           | 0                                  | 0                          | 0                            | 0                            | 0                                | 0                          | 0                            | 0                                 | 0                             | 0                               | 0                            | 0                           | 0                           | 0                                   | 0                            | 0                        | 0                                       | 0                                  | 0                        | 0                           | 0                          | 0                                 | 0                              | 0                            | 0                                 | 0                                     | 0                                  | 0                         | 0                                   | 0                                  | 0                            | 0                         | 0                        | 0                              | 0                                | 0                            | 0                            | 0                              | 0                           | 0                           |
| 1           | 61481          | 46    | 1               | 2                 | 1                      | 2               | 0.317083              | 0.323944     | 2                     | 0          | 1          | 1                 | 0                 | 0                     | 0                           | 0                       | 1                           | 0                               | 0                     | 0                       | 0                   | 0                         | 1                           | 0                             | 0                          | 0                          | 0                           | 1                                  | 0                                 | 0                           | 0                           | 0                           | 0                          | 0                               | 0                                    | 0                              | 0                                     | 1                           | 0                           | 0                           | 0                                   | 0                           | 0                           | 0                                  | 0                          | 0                            | 0                            | 0                                | 0                          | 0                            | 0                                 | 0                             | 0                               | 0                            | 0                           | 0                           | 0                                   | 0                            | 0                        | 0                                       | 0                                  | 0                        | 0                           | 0                          | 0                                 | 0                              | 0                            | 0                                 | 0                                     | 0                                  | 0                         | 0                                   | 0                                  | 0                            | 0                         | 0                        | 0                              | 0                                | 0                            | 0                            | 0                              | 0                           | 0                           |
| 1           | 51804          | 49    | 1               | 1                 | 0                      | 0               | 0.231958              | 0.366197     | 1                     | 0          | 1          | 0                 | 1                 | 0                     | 0                           | 0                       | 1                           | 0                               | 0                     | 0                       | 0                   | 0                         | 1                           | 0                             | 0                          | 0                          | 1                           | 0                                  | 0                                 | 0                           | 0                           | 0                           | 0                          | 0                               | 0                                    | 0                              | 0                                     | 0                           | 0                           | 0                           | 0                                   | 0                           | 0                           | 0                                  | 0                          | 0                            | 0                            | 0                                | 0                          | 0                            | 0                                 | 0                             | 0                               | 0                            | 0                           | 0                           | 0                                   | 0                            | 0                        | 1                                       | 0                                  | 0                        | 0                           | 0                          | 0                                 | 0                              | 0                            | 0                                 | 0                                     | 0                                  | 0                         | 0                                   | 0                                  | 0                            | 0                         | 0                        | 0                              | 0                                | 0                            | 0                            | 0                              | 0                           | 0                           |